# Generated by Django 3.2.18 on 2023-04-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_product_cat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cat_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
